### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/caminte-cli/bin/../templates/Model.ejs'

### ISSUE THREAD

**Issue by fobo66** [biggora/caminte-cli#5]
When I'm trying to init my models, I get this error:

```
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/caminte-cli/bin/../templates/Model.ejs'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/caminte-cli/bin/caminte:60:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)

```

Platform: Ubuntu 16.04 amd64, caminte-cli@1.3.1

**Comment by ghost** [comment]
Same error
